@startuml

title __INDEXES's Class Diagram__\n

  package com.voicenotes {
    package com.voicenotes.view.utils {
      package com.voicenotes.view.utils.indexes {
        class AudioIndexer {
            {static} + LOG_TAG : String
            {static} - writer : IndexWriter
            {static} - analyzer : Analyzer
            {static} - indexDir : Directory
            {static} - iwc : IndexWriterConfig
            {static} ~ f : File
            - textsPath : String
            {static} ~ context : Context
            {static} + initialize()
            {static} + deleteFromIndex()
            {static} + close()
            {static} + getDocument()
            + createIndex()
            {static} + indexDoc()
        }
      }
    }
  }
  

  package com.voicenotes {
    package com.voicenotes.view.utils {
      package com.voicenotes.view.utils.indexes {
        class AudioSearcher {
            {static} + MAX_SEARCH : int
            ~ indexSearcher : IndexSearcher
            ~ indexDir : Directory
            ~ reader : IndexReader
            ~ queryParser : MultiFieldQueryParser
            ~ query : Query
            + AudioSearcher()
            + search()
            + getDocument()
            + close()
        }
      }
    }
  }
  

  package com.voicenotes {
    package com.voicenotes.view.utils {
      package com.voicenotes.view.utils.indexes {
        class LuceneConstants {
            {static} + CONTENTS : String
            {static} + FILE_NAME : String
            {static} + FILE_PATH : String
            {static} + MAX_SEARCH : int
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
